title: "Wavetable合成の為のアトリビュート操作型CVAEエフェクターの検討"
description: 湯谷 承将 <sup> 1 </sup>, 山本 雄也<sup> 1 </sup>, 中谷 秀洋<sup> 2 </sup>, 寺澤 洋子<sup> 1 </sup> <br> <sup> 1</sup> 筑波大学, <sup> 2 </sup> サイボウズ・ラボ
theme: jekyll-theme-cayman

colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
